[simulation]
imaginary = 2
iterations = 1000
time_step = 0.01
mass = 1
log_interval = 200

[grid]
bounds = [[-8, 8], [-8, 8]]
npoint = 128

[initial_conditions]
position = [1, 1]
momentum = [0, 0]
gamma = [2, 2]

[potential]
name = "harmonic"
