[simulation]
iterations = 3000
time_step = 1
mass = 2000
adiabatic = true
log_interval = 500

[grid]
bounds = [[-24.0, 32.0]]
npoint = 2048

[initial_conditions]
position = [-10]
momentum = [15]
gamma = [2]
state = 1
adiabatic = true

[potential]
name = "tully_1"
