title: Zinq
email: tom.jira@gmail.com
github_username: tjira

url: "https://tjira.github.io"
baseurl: "/zinq"

theme: just-the-docs

callouts:
    cite:
        title: Cite
        color: yellow
    definition:
        title: Definition
        color: blue

aux_links:
  "Zinq on GitHub":
    - "//github.com/tjira/zinq"
