name: Library

on: workflow_dispatch

permissions:
  contents: read

jobs:
  compile:
    name: ${{matrix.os}} / ${{matrix.target}}-${{matrix.suffix}}
    runs-on: ${{matrix.os}}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-linux
            build_flags: "--shared"
            suffix: "gnu"
          - os: ubuntu-latest
            target: x86_64-linux
            build_flags: ""
            suffix: "musl"
          - os: ubuntu-latest
            target: aarch64-linux
            build_flags: "--shared"
            suffix: "gnu"
          - os: ubuntu-latest
            target: aarch64-linux
            build_flags: ""
            suffix: "musl"

    steps:
      - uses: actions/checkout@v7

      - name: Setup Zig
        uses: mlugg/setup-zig@v2
        with:
          version: 0.16.0

      - name: Compile Libraries
        run: ./script/library.pl --target ${{matrix.target}} ${{matrix.build_flags}} --generic

      - name: Remove Unnecessary Files
        working-directory: external-${{matrix.target}}-${{matrix.suffix}}
        run: rm -rf bin share lib/cmake lib/pkgconfig include/*.bib include/*.f03 lib/*.la

      - name: Remove Eigen Signature File
        working-directory: external-${{matrix.target}}-${{matrix.suffix}}
        run: rm -f include/eigen3/signature_of_eigen3_matrix_library

      - name: Prepare Artifact Directory
        run: mkdir -p staging && mv external-${{matrix.target}}-${{matrix.suffix}} staging
      
      - name: Upload Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: external-${{matrix.target}}-${{matrix.suffix}}
          path: staging
