name: Library

on: workflow_dispatch

permissions:
  contents: read

jobs:
  compile:
    name: ${{matrix.os}} / ${{matrix.target}}-${{matrix.suffix}}
    runs-on: ${{matrix.os}}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-linux
            build_flags: "--shared"
            suffix: "gnu"
          - os: ubuntu-latest
            target: x86_64-linux
            build_flags: ""
            suffix: "musl"
          - os: ubuntu-latest
            target: aarch64-linux
            build_flags: "--shared"
            suffix: "gnu"
          - os: ubuntu-latest
            target: aarch64-linux
            build_flags: ""
            suffix: "musl"

    steps:
      - uses: actions/checkout@v7

      - name: Setup Zig
        uses: mlugg/setup-zig@v2
        with:
          version: 0.16.0

      - name: Compile Libraries
        run: ./script/library.pl --target ${{matrix.target}} ${{matrix.build_flags}}
      
      - name: Upload Artifacts
        uses: actions/upload-artifact@v7
        with:
          path: external-${{matrix.target}}-${{matrix.suffix}}
