name: Library

on: workflow_dispatch

permissions:
  contents: read

jobs:
  compile:
    name: ${{matrix.os}} / ${{matrix.target}}
    runs-on: ${{matrix.os}}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-linux
          - os: ubuntu-latest
            target: aarch64-linux
          - os: ubuntu-latest
            target: x86_64-macos
          - os: ubuntu-latest
            target: aarch64-macos
          - os: ubuntu-latest
            target: x86_64-windows
          - os: ubuntu-latest
            target: aarch64-windows

    steps:
      - uses: actions/checkout@v7

      - name: Setup Zig
        uses: mlugg/setup-zig@v2
        with:
          version: 0.16.0

      - name: Cache Compiled Libraries
        id: cache-libs
        uses: actions/cache@v4
        with:
          path: external-${{matrix.target}}
          key: libs-${{matrix.target}}-${{hashFiles('script/library.pl')}}

      - name: Install Dependencies
        if: steps.cache-libs.outputs.cache-hit != 'true'
        run: sudo apt-get install libarchive-tools

      - name: Install Boost
        id: install-boost
        if: steps.cache-libs.outputs.cache-hit != 'true'
        uses: MarkusJx/install-boost@v2
        with:
          boost_version: 1.83.0
          platform_version: 22.04

      - name: Compile Libraries
        if: steps.cache-libs.outputs.cache-hit != 'true'
        env:
          BOOST_ROOT: ${{steps.install-boost.outputs.BOOST_ROOT}}
        run: ./script/library.pl --target ${{matrix.target}} --generic

      - name: Remove Unnecessary Files
        working-directory: external-${{matrix.target}}
        run: rm -rf bin share lib/cmake lib/pkgconfig include/*.bib include/*.f03 lib/*.la

      - name: Remove Eigen Signature File
        working-directory: external-${{matrix.target}}
        run: rm -f include/eigen3/signature_of_eigen3_matrix_library

      - name: Prepare Artifact Directory
        run: mkdir -p staging && mv external-${{matrix.target}} staging
      
      - name: Upload Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: external-${{matrix.target}}
          path: staging
