name: Test

on:
  push:
    branches:
      - '*'

permissions:
  contents: read

jobs:
  linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Setup Zig
        uses: mlugg/setup-zig@v2
        with:
          version: 0.15.2

      - name: Run Tests in ReleaseFast Mode
        run: zig build --release=fast test

      - name: Setup Tmate Session
        if: failure()
        uses: mxschmitt/action-tmate/detached@v3

  macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v6

      - name: Setup Zig
        uses: mlugg/setup-zig@v2
        with:
          version: 0.15.2

      - name: Run Tests in ReleaseFast Mode
        run: zig build --release=fast test

      - name: Setup Tmate Session
        if: failure()
        uses: mxschmitt/action-tmate/detached@v3

  windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v6

      - name: Setup Zig
        uses: mlugg/setup-zig@v2
        with:
          version: 0.15.2

      - name: Run Tests in ReleaseFast Mode
        run: zig build --release=fast test

      - name: Setup Tmate Session
        if: failure()
        uses: mxschmitt/action-tmate/detached@v3
