name: Test

on:
  push:
    branches:
      - '*'

permissions:
  contents: read

jobs:
  test:
    name: ${{matrix.os}} / ${{matrix.mode_name}}
    runs-on: ${{matrix.os}}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            mode_name: Debug
            build_flags: ""
          - os: ubuntu-latest
            mode_name: ReleaseFast
            build_flags: "--release=fast"
          - os: ubuntu-latest
            mode_name: ReleaseSafe
            build_flags: "--release=safe"
          - os: ubuntu-latest
            mode_name: ReleaseSmall
            build_flags: "--release=small"
          - os: macos-latest
            mode_name: Debug
            build_flags: ""
          - os: macos-latest
            mode_name: ReleaseFast
            build_flags: "--release=fast"
          - os: macos-latest
            mode_name: ReleaseSafe
            build_flags: "--release=safe"
          - os: macos-latest
            mode_name: ReleaseSmall
            build_flags: "--release=small"
          - os: windows-latest
            mode_name: Debug
            build_flags: ""
          - os: windows-latest
            mode_name: ReleaseFast
            build_flags: "--release=fast"
          - os: windows-latest
            mode_name: ReleaseSafe
            build_flags: "--release=safe"
          - os: windows-latest
            mode_name: ReleaseSmall
            build_flags: "--release=small"
          - os: ubuntu-latest
            mode_name: Debug Libc
            build_flags: "-Duse-xc=true"
          - os: ubuntu-latest
            mode_name: ReleaseFast Libc
            build_flags: "-Duse-xc=true --release=fast"
          - os: ubuntu-latest
            mode_name: ReleaseSafe Libc
            build_flags: "-Duse-xc=true --release=safe"
          - os: ubuntu-latest
            mode_name: ReleaseSmall Libc
            build_flags: "-Duse-xc=true --release=small"

    steps:
      - uses: actions/checkout@v6

      - name: Setup Zig
        uses: mlugg/setup-zig@v2
        with:
          version: 0.15.2

      - name: Compile libxc
        if: contains(matrix.build_flags, 'use-xc')
        run: ./script/compile_libs.sh

      - name: Run Tests in ${{matrix.mode_name}} Mode
        run: zig build ${{matrix.build_flags}} test

      - name: Setup Tmate Session
        if: failure()
        uses: mxschmitt/action-tmate/detached@v3
