name: Test

on:
  push:
    branches:
      - '*'

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        julia-version: ['1.11', '1.12']

    steps:
      - uses: actions/checkout@v6

      - name: Set up Julia
        uses: julia-actions/setup-julia@v3
        with:
          version: ${{matrix.julia-version}}

      - name: Cache dependencies
        uses: julia-actions/cache@v3

      - name: Remove the Manifest
        run: rm Manifest.toml

      - name: Insantiate the Project
        uses: julia-actions/julia-buildpkg@v1

      - name: Run Tests
        uses: julia-actions/julia-runtest@v1
