name: Twine

on:
  push:
    tags:
      - 'v**'

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Python Packages
        run: pip install build setuptools wheel pkginfo==1.12 twine==6.0.1

      - name: Build the Wheel and Source Distribution
        run: make wheel

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: ${{secrets.TWINE_USERNAME}}
          TWINE_PASSWORD: ${{secrets.TWINE_PASSWORD}}
        run: twine upload dist/*

      - name: Setup Tmate Session
        if: failure()
        uses: mxschmitt/action-tmate/detached@v3
