name: Twine

on:
  push:
    tags:
      - 'v**'

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Python Packages
        run: pip install build setuptools wheel twine

      - name: Build the Wheel and Source Distribution
        run: make wheel

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: ${{secrets.PYPI_USERNAME}}
          TWINE_PASSWORD: ${{secrets.PYPI_PASSWORD}}
        run: twine upload dist/*
